name: "fastapi"
services:
   api:
      build:
         context: .
         dockerfile: Dockerfile.dev
      ports:
         - "8000:8000"
      networks:
         - my-api-net
      depends_on:
         - postgres_db
      volumes:
      - ./do_app:/do-app                 # : right side is the path inside the container
# host machine (where Docker is running)   :       
   postgres_db:
      image: postgres:latest
      restart: always
      container_name: PostgresCount
      environment:
         # - name=value
         - POSTGRES_USER=ammar
         - POSTGRES_PASSWORD=my_password
         - POSTGRES_DB=mydatabase
      ports:
         - "5442:5432"
      volumes:
         # - volumeName:containerPath:ro     -> ro -> read only
         - postgres_db:/var/lib/postgresql/data
      networks:
         - my-api-net

volumes:
   postgres_db:
      driver: local
networks:
   my-api-net:
