# Use an official Python runtime as a parent image
FROM python:3.12

# Label the maintainer
LABEL maintainer="ammara-gul"

# Set the working directory in the container
WORKDIR /do-app

# Install Poetry
RUN pip install poetry

# Copy the current directory contents into the container at /do-app
COPY . /do-app/

# Configuration to avoid creating virtual environments inside the Docker container
RUN poetry config virtualenvs.create false

# Install dependencies including development ones
RUN poetry install

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Run the app. CMD can be overridden when starting the container
CMD ["poetry", "run", "uvicorn", "do_app.main:app", "--host", "0.0.0.0", "--reload"]
